language: java

dist: focal

# Remove this if using external Travis
group: focal

jdk:
  - openjdk11

notifications:
  email: true

env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"

branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"

jobs:
  include:
    - stage: Build & Test
      script:
        -  mvn clean verify $MVN_ARGS
    - stage: Run Java System Test
      env: API_FOLDER=tests
    - env: API_FOLDER=apidocs

before_install:
  - sudo apt-get update
  - echo -e "machine github.ibm.com\n  login $GITHUB_ACCESS_TOKEN" > ~/.netrc
  # Install maven - temporary until Travis focal image is fixed.
  - wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
  - tar -zxf apache-maven-3.9.6-bin.tar.gz
  - export MAVEN_HOME=$PWD/apache-maven-3.9.6
  - export PATH=${MAVEN_HOME}/bin:$PATH
  - which mvn
  - mvn -v

install: true

script:
  - |
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
       echo "Running Java System Test using API folder: $API_FOLDER"
       git clone https://github.ibm.com/CloudEngineering/sdkgen-systest.git
       cd sdkgen-systest
       ./install_scripts/install_deps_ubuntu.sh
       ./setup_and_generate.sh -l ibm-java -t $TRAVIS_BRANCH -s -i $API_FOLDER
    else
       echo "Skipping systest stage for PR build."
    fi
