name: GitHub CI
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
    - name: Set Maven version
      run: ./build/setMavenVersion.sh
    - name: Build and Test with Maven
      run: mvn verify -fae -DskipITs
